INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Army Selection Center Quetta', 'Static/Digital Billboard', 'Pakistan', 'Rs 400,000', 400000.0, '60x20 Zone', '3SZ0D Featured Discounted Price Premium Location Rs 1,500,000 Bridge Panel At Korangi Road Near NMC Signal', 'Yes', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%20883%20580%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Army Selection Center Quetta', 'Static/Digital Billboard', 'Pakistan', 'Rs 400,000', 400000.0, '60x20 Zone', '3SZ0D', 'No', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%20883%20580%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Army Selection Center Quetta', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, '60x20 Zone', '3SZ0D', 'No', 'Login to view date', '', 'https://www.adbuq.com/billboards/billboard-at-army-selection-center-quetta/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Bridge Panel At Korangi Road Near NMC Signal (2) Karachi', 'Static/Digital Billboard', 'Pakistan', 'Rs 1,500,000', 1500000.0, 'Very Large Zone', 'reconfirm', 'No', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%201598%20875%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Bridge Panel At Korangi Road Near NMC Signal (2) Karachi', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, 'Very Large Zone', 'reconfirm', 'No', 'Login to view date', '', 'https://www.adbuq.com/billboards/bridge-panel-at-korangi-road-near-nmc-signal-2-karachi/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Chungi # 8 Kacheri Flyover Multan', 'Static/Digital Billboard', 'Pakistan', 'Rs 150,000', 150000.0, '40x15 Zone', 'KPUVT', 'No', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%20880%20564%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Chungi # 8 Kacheri Flyover Multan', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, '40x15 Zone', 'KPUVT', 'No', 'Login to view date', '', 'https://www.adbuq.com/billboards/billboard-at-chungi-8-katchery-flyover-multan/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard at Ammar Chowk Grid Station Rawalpindi', 'Static/Digital Billboard', 'Pakistan', 'Rs 1,250,000', 1250000.0, '60x20 Zone', '6O0FH , 1DS4Z2 , NDW9T', 'No', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%202001%201245%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard at Ammar Chowk Grid Station Rawalpindi', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, '60x20 Zone', '6O0FH , 1DS4Z2 , NDW9T', 'No', 'Login to view date', '', 'https://www.adbuq.com/billboards/billboard-at-ammar-chowk-grid-station-rawalpindi/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Fortress Chowk Signal Cantt (With Lights) Lahore', 'Static/Digital Billboard', 'Pakistan', 'Rs 2,200,000', 2200000.0, '60x20 Zone', '5RL2S Extendable', 'Yes', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%201533%20909%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard At Fortress Chowk Signal Cantt (With Lights) Lahore', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, '60x20 Zone', '5RL2S Extendable', 'Yes', 'Login to view date', '', 'https://www.adbuq.com/billboards/billboard-at-fortress-chowk-signal-cantt-with-lights-lahore/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard on Saddar Road Stadium Chowk Peshawar', 'Static/Digital Billboard', 'Pakistan', 'Rs 550,000', 550000.0, '60x20 Zone', 'VDWCY', 'No', 'Login to view date', 'data:image/svg+xml,%3Csvg%20viewBox%3D%220%200%201920%201167%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3C%2Fsvg%3E', 'https://www.adbuq.com/label/discount/');
INSERT INTO billboards (title, media_type, city, price, numeric_price, size, zone, extendable, availability_status, image_url, detail_url)
VALUES ('Billboard on Saddar Road Stadium Chowk Peshawar', 'Static/Digital Billboard', 'Pakistan', 'N/A', 0.0, '60x20 Zone', 'VDWCY', 'No', 'Login to view date', '', 'https://www.adbuq.com/billboards/billboard-on-saddar-road-stadium-chowk-peshawar/');